django_simple_forum/urls.py
from django.urls import path
from . import  views

app_name = 'django_simple_forum'
urlpatterns = [

    path(r'', views.TopicList.as_view(), name="topic_list"),
    path(r'register/', views.IndexView.as_view(), name="signup"),
    # path(r'^forum/login/$', views.user_login, name="user_login"),
    # path(r'^fb_login/$', views.facebook_login, name="facebook_login"),
    # path(r'^gp_login/$', views.google_login, name="google_login"),
    # path('', views.TopicList.as_view(), name="topic_list"),
    # path('register/', views.IndexView.as_view(), name="signup"),
    path('forum/login/', views.ForumLoginView.as_view(), name="user_login"),
    # path('fb_login/', views.facebook_login, name="facebook_login"),
    # path('gp_login/', views.google_login, name="google_login"),

    path('topic/add/', views.TopicAdd.as_view(), name="new_topic"),
    path('topic/<slug:slug>/update/', views.TopicUpdateView.as_view(), name="topic_update"),
    path('topic/view/<slug:slug>/', views.TopicView.as_view(), name="view_topic"),
    path('topic/like/<slug:slug>/', views.TopicLike.as_view(), name="like_topic"),
    path('topic/follow/<slug:slug>/', views.TopicFollow.as_view(), name="follow_topic"),
    path('topic/votes/<slug:slug>/up/', views.TopicVoteUpView.as_view(), name="topic_vote_up"),
    path('topic/votes/<slug:slug>/down/', views.TopicVoteDownView.as_view(), name="topic_vote_down"),

    path('mentioned-users/<int:topic_id>/', views.get_mentioned_user, name="get_mentioned_user"),
    path('user/profile/<slug:user_name>/', views.ProfileView.as_view(), name="view_profile"),
    path('change-password/', views.UserChangePassword.as_view(), name="user_change_password"),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name="forgot_password"),
    path('comment/delete/<int:comment_id>/',views.CommentDelete.as_view(), name="comment_delete"),
    # path('comment/delete/<int:comment_id>/', views.delete_comment, name="comment_delete"),
    path('comment/edit/<int:comment_id>', views.CommentEdit.as_view(), name="comment_edit"),

    path('categories/', views.ForumCategoryList.as_view(), name="forum_categories"),
    path('tags/', views.ForumTagsList.as_view(), name="forum_tags"),
    path('badges/', views.ForumBadgeList.as_view(), name="forum_badges"),
    path('profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('upload/profile-pic/', views.UserProfilePicView.as_view(), name="user_profile_pic"),
    path('send-mail/settings/', views.UserSettingsView.as_view(), name="user_settings"),

    path('category/<slug:slug>', views.ForumCategoryView.as_view(), name="forum_category_detail"),
    path('tags/<slug:slug>', views.ForumTagsView.as_view(), name="forum_tags_detail"),

    path('user/<slug:user_name>/', views.UserDetailView.as_view(), name="user_details"),

    path('comment/add/', views.CommentAdd.as_view(), name="new_comment"),
    path('comment/votes/<int:pk>/up/', views.CommentVoteUpView.as_view(), name="comment_vote_up"),
    path('comment/votes/<int:pk>/down/', views.CommentVoteDownView.as_view(), name="comment_vote_down"),


    #url('dashboard/', views.LoginView.as_view(), name="dashboard"),
    path(r'dashboard/', views.DashboardView.as_view(), name="dashboard"),
    # path('logout/', views.getout, name='out'),

    # path('dashboard/', views.LoginView.as_view(), name="dashboard"),
    # path('dashboard/$', DashboardView.as_view(), name="dashboard"),
    path('logout/', views.getout, name='out'),

    path('dashboard/category/list/', views.CategoryList.as_view(), name="categories"),
    path('dashboard/category/add/', views.CategoryAdd.as_view(), name="add_category"),
    path('dashboard/category/delete/<slug:slug>',
        views.CategoryDelete.as_view(), name="delete_category"),
    path('dashboard/category/edit/<slug:slug>',
        views.CategoryEdit.as_view(), name="edit_category"),
    path('dashboard/category/view/<slug:slug>',
        views.CategoryDetailView.as_view(), name="view_category"),

    path('dashboard/badge/list/', views.BadgeList.as_view(), name="badges"),
    path('dashboard/badge/add/', views.BadgeAdd.as_view(), name="add_badge"),
    path('dashboard/badge/delete/<slug:slug>', views.BadgeDelete.as_view(), name="delete_badge"),
    path('dashboard/badge/edit/<slug:slug>', views.BadgeEdit.as_view(), name="edit_badge"),
    path('dashboard/badge/view/<slug:slug>/', views.BadgeDetailView.as_view(), name="view_badge"),

    path('dashboard/users/list/', views.UserList.as_view(), name="users"),
    path('dashboard/users/delete/<int:user_id>/',
        views.DashboardUserDelete.as_view(), name="delete_user"),
    path('dashboard/users/status/<int:user_id>/',
        views.UserStatus.as_view(), name="user_status"),
    path('dashboard/users/view/<int:user_id>/',
        views.UserDetail.as_view(), name="user_detail"),
    path('dashboard/users/edit/<int:user_id>/',
        views.DashboardUserEdit.as_view(), name="edit_user"),

    path('dashboard/topics/list/', views.DashboardTopicList.as_view(), name="topics"),
    path('dashboard/topics/delete/<slug:slug>/', views.TopicDeleteView.as_view(), name="delete_topic"),
    path('dashboard/topic/view/<slug:slug>/', views.TopicDetail.as_view(), name="topic_detail"),
    path('dashboard/topic/status/<slug:slug>/', views.TopicStatus.as_view(), name="topic_status"),

    path('dashboard/change-password/', views.ChangePassword.as_view(), name="change_password"),

]

djangoafrica/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django. urls import path, include
# from django.conf.urls import url
from homepage.views import HomeView 
from blog.views import ckeditor_form_view, PostDetailView
from django.contrib.auth import views as auth_views

# from mysite.core import views as core_views


app_name = "django_africa"
urlpatterns = [
    path('', HomeView.as_view(), name='home_view'),
    path('blog/', ckeditor_form_view, name='ckeditor-form'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/<int:pk>/<slug:slug>/', PostDetailView.as_view(), 
    name='detail'),
    path('xxxxhas2/', admin.site.urls),
    path('forum/', include('django_simple_forum.urls')),
    # path('', core_views.home, name='home'),
    # path (r'^login/$', auth_views.login, name='login'),
    # path(r'^logout/$', auth_views.logout, name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),

] + static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_simple_forum/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
import hashlib
from datetime import datetime

STATUS = (
    ('Draft', 'Draft'),
    ('Published', 'Published'),
    ('Disabled', 'Disabled'),
)

USER_ROLES = (
    ('Admin', 'Admin'),
    ('Publisher', 'Publisher'),
)

User = settings.AUTH_USER_MODEL


# tags created for topic
class Tags(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50, unique=True)

    def get_topics(self):
        topics = Topic.objects.filter(tags__in=[self], status='Published')
        return topics


# tags created for topic
class Badge(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50, unique=True)

    def get_users(self):
        user_profile = UserProfile.objects.filter(badges__in=[self])
        return user_profile


def img_url(self, filename):
    hash_ = hashlib.md5()
    hash_.update(
        str(filename).encode('utf-8') + str(datetime.now()).encode('utf-8'))
    file_hash = hash_.hexdigest()
    return "%s%s/%s" % (self.file_prepend, file_hash, filename)


# user profile to store no of votes available to user, badges for a topic, user roles,
class UserProfile(models.Model):
    file_prepend = "forum_user/profilepics/"
    
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    used_votes = models.IntegerField(default='0')
    user_roles = models.CharField(choices=USER_ROLES, max_length=10)
    badges = models.ManyToManyField(Badge)
    profile_pic = models.FileField(
        max_length=500, null=True, blank=True, upload_to=img_url)
    send_mailnotifications = models.BooleanField(default=False)

    # need to add social details for a user if we implement socail login

    def get_no_of_up_votes(self):
        user_topics = UserTopics.objects.filter(user=self.user)
        votes = 0
        for topic in user_topics:
            votes += topic.no_of_votes
        return votes

    def get_no_of_down_votes(self):
        user_topics = UserTopics.objects.filter(user=self.user)
        votes = 0
        for topic in user_topics:
            votes += topic.no_of_down_votes
        return votes

    def get_topics(self):
        topics = Topic.objects.filter(created_by=self.user)
        return topics

    def get_followed_topics(self):
        topics = UserTopics.objects.filter(user=self.user, is_followed=True)
        topics = Topic.objects.filter(id__in=topics.values_list('topic', flat=True))
        return topics

    def get_liked_topics(self):
        topics = UserTopics.objects.filter(user=self.user, is_like=True)
        topics = Topic.objects.filter(id__in=topics.values_list('topic', flat=True))
        return topics

    def get_timeline(self):
        timeline = Timeline.objects.filter(user=self.user).order_by('-created_on')
        return timeline

    def get_user_topic_tags(self):
        tags = Tags.objects.filter(id__in=self.get_topics().values_list('tags', flat=True))
        return tags

    def get_user_topic_categories(self):
        categories = ForumCategory.objects.filter(id__in=self.get_topics().values_list('category', flat=True))
        return categories
        # return []

    def get_user_suggested_topics(self):
        categories = ForumCategory.objects.filter(id__in=self.get_topics().values_list('category', flat=True))
        topics = Topic.objects.filter(category__id__in=categories.values_list('id', flat=True))
        return topics
        # return []


class ForumCategory(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,)
    title = models.CharField(max_length=1000)
    is_active = models.BooleanField(default=False)
    color = models.CharField(max_length=20, default="#999999")
    is_votable = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=1000)
    description = models.TextField()
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, )

    def get_topics(self):
        topics = Topic.objects.filter(category=self, status='Published')
        return topics

    def __str__(self):
        return self.title


class Vote(models.Model):
    TYPES = (
        ("U", "Up"),
        ("D", "Down"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    type = models.CharField(choices=TYPES, max_length=1)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

class Topic(models.Model):
    title = models.CharField(max_length=2000)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,)
    status = models.CharField(choices=STATUS, max_length=10)
    category = models.ForeignKey(ForumCategory, on_delete=models.CASCADE,)
    created_on = models.DateTimeField(auto_now=True)
    updated_on = models.DateTimeField(auto_now=True)
    no_of_views = models.IntegerField(default='0')
    slug = models.SlugField(max_length=1000)
    tags = models.ManyToManyField(Tags)
    no_of_likes = models.IntegerField(default='0')
    votes = models.ManyToManyField(Vote)

    def get_comments(self):
        comments = Comment.objects.filter(topic=self, parent=None)
        return comments

    def get_all_comments(self):
        comments = Comment.objects.filter(topic=self)
        return comments

    def get_last_comment(self):
        comments = Comment.objects.filter(topic=self).order_by('-updated_on').first()
        return comments

    def get_topic_users(self):
        comment_user_ids = Comment.objects.filter(topic=self).values_list('commented_by', flat=True)
        liked_users_ids = UserTopics.objects.filter(topic=self, is_like=True).values_list('user', flat=True)
        followed_users = UserTopics.objects.filter(topic=self, is_followed=True).values_list('user', flat=True)
        all_users = list(comment_user_ids) + list(liked_users_ids) + list(followed_users) + [self.created_by.id]
        users = UserProfile.objects.filter(user_id__in=set(all_users))
        return users

    # def get_total_of_votes(self):
    #     no_of_votes = self.no_of_votes + self.no_of_down_votes
    #     return no_of_votes

    def up_votes_count(self):
        return self.votes.filter(type="U").count()

    def down_votes_count(self):
        return self.votes.filter(type="D").count()  

    def __str__(self):
        return self.title      

# user followed topics
class UserTopics(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,)
    is_followed = models.BooleanField(default=False)
    followed_on = models.DateField(null=True, blank=True)
    no_of_votes = models.IntegerField(default='0')
    no_of_down_votes = models.IntegerField(default='0')
    is_like = models.BooleanField(default=False)


class Comment(models.Model):
    comment = models.TextField(null=True, blank=True)
    commented_by = models.ForeignKey(User, related_name="commented_by", on_delete=models.CASCADE,)
    topic = models.ForeignKey(Topic, related_name="topic_comments", on_delete=models.CASCADE,)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey("self", blank=True, null=True, related_name="comment_parent", on_delete=models.CASCADE, )
    mentioned = models.ManyToManyField(User, related_name="mentioned_users")
    votes = models.ManyToManyField(Vote)

    def get_comments(self):
        comments = self.comment_parent.all()
        return comments

    def up_votes_count(self):
        return self.votes.filter(type="U").count()

    def down_votes_count(self):
        return self.votes.filter(type="D").count()


# user activity
class Timeline(models.Model):
    content_type = models.ForeignKey(ContentType, related_name="content_type_timelines", on_delete=models.CASCADE, )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    namespace = models.CharField(max_length=250, default="default", db_index=True)
    event_type = models.CharField(max_length=250, db_index=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE,)
    data = models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        index_together = [("content_type", "object_id", "namespace"), ]
        ordering = ['-created_on']


class Attachment(models.Model):
    file_prepend = "forum_topic/attachments/"
    uploaded_by = models.ForeignKey(User, related_name='attachments_user', on_delete=models.CASCADE,)
    created_on = models.DateTimeField(auto_now_add=True)
    attached_file = models.FileField(
        max_length=500, null=True, blank=True, upload_to=img_url)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE,)


class Facebook(models.Model):
    user = models.ForeignKey(User, related_name='user_facebook',on_delete=models.CASCADE, )
    facebook_id = models.CharField(max_length=100)
    facebook_url = models.CharField(max_length=200, default='')
    first_name = models.CharField(max_length=200, default='')
    last_name = models.CharField(max_length=200, default='')
    verified = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    language = models.CharField(max_length=200, default='')
    hometown = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='', db_index=True)
    gender = models.CharField(max_length=200, default='')
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=200, default='')

django_simple_forum/templates/dashboard/badges.html
{% extends 'dashboard/dashboard_base.html' %}
{% load el_pagination_tags %}
{% block stage %}
<div class="content">
  <div class="list">
    <div class="list-header">
      <label>Badges List <span class="pull-right"><a href="{% url "django_simple_forum:add_badge" %}" class=""><i class="fa fa-user-plus view"></i>New Badge</a></span></label>
    </div>
    <div class="results-slct-items row mt">
      {% paginate 10 badges_list %}
      <div class="col-md-6 col-xs-6 page-items">
        Per Page
        <select id="pagination_per_page">
        <option value="10" {% if per_page == "10" %}selected{% endif %}>10</option>
        <option value="20" {% if per_page == "20" %}selected{% endif %}>20</option>
        <option value="50" {% if per_page == "50" %}selected{% endif %}>40</option>
        <option value="100" {% if per_page == "100" %}selected{% endif %}>40</option>
        </select>
      </div>
      <form name="filter_form" id="filter_form" method='post'>
        {% csrf_token %}
        <input type="text" name="search_text" id="search_text" value="{{ request.POST.search_text }}"/>
        <input type="hidden" name="filter_per_page" id="filter_per_page" value="{{ filter_per_page }}"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    {% if badges_list %}
    <div class="user_table">
      <div class="table-responsive">

    <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody class="overflow:scroll;">
                        {% for badge in badges_list %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td>{{ badge.id }}</td>
                          <td>{{ badge.title }}</td>
                          <td><a href="{% url "django_simple_forum:view_badge" badge.slug %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_badge" badge.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_badge" badge.slug %}" class="delete-badge"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    {% show_pages %}
      </div>
    </div>
    <nav class="overview-paging">
    </nav>
        {% else %}
    No Badge Available in database
    {% endif %}

  </div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.delete-badge').click(function(e){
  e.preventDefault();
  href = $(this).attr('data-href');
  if (!confirm('Do you want to delete Badge?'))
    return;
  $.post(href, $("form#jobform").serialize(), function(data) {
      if (data.error) {
        alert(data.response);
      } else {
        alert("Badge Deleted Successfully")
        window.location = '.';
      }
    }, 'json');
  });

</script>
{% endblock %}

django_simple_forum/templates/dashboard/categories.html
{% extends 'dashboard/dashboard_base.html' %}
{% load el_pagination_tags %}
{% block stage %}
<div class="content">
  <div class="list">
    <div class="list-header">
      <label>Categories <span class="pull-right"><a href="{% url "django_simple_forum:add_category" %}" class=""><i class="fa fa-user-plus view"></i>New Category</a></span></label>
    </div>
    <div class="results-slct-items row mt">
      {% paginate 10 categories_list %}
      <div class="col-md-6 col-xs-6 page-items">
        Per Page
        <select id="pagination_per_page">
        <option value="10" {% if per_page == "10" %}selected{% endif %}>10</option>
        <option value="20" {% if per_page == "20" %}selected{% endif %}>20</option>
        <option value="50" {% if per_page == "50" %}selected{% endif %}>40</option>
        <option value="100" {% if per_page == "100" %}selected{% endif %}>40</option>
        </select>
      </div>
      <form name="filter_form" id="filter_form" method='post'>
        {% csrf_token %}
        <input type="text" name="search_text" id="search_text" value="{{ request.POST.search_text }}"/>
        <input type="hidden" name="filter_per_page" id="filter_per_page" value="{{ filter_per_page }}"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    {% if categories_list %}
        <div class="user_table">
      <div class="table-responsive">

    <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Color</th>
                          <th>Created By</th>
                          <th>Is Votable</th>
                          <th>Is Active</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody class="overflow:scroll;">
                        {% for category in categories_list %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td>{{ forloop.counter }}</td>
                          <td>{%if category.parent%}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{%endif%}{{ category.title }}</td>
                          <td><input type="color" name="color" id="color" value="{{ category.color }}" disabled></td>
                          <td>{{ category.created_by }}</td>
                          <td>{% if category.is_votable %}True{% else %}False{% endif %}</td>
                          <td>{% if category.is_active %}True{% else %}False{% endif %}</td>
                          <td><a href="{% url "django_simple_forum:view_category" category.slug %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_category" category.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_category" category.slug %}" class="delete-category"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% for sub_category in category.forumcategory_set.all %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td></td>
                          <td>{%if sub_category.parent%}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{%endif%}{{ sub_category.title }}</td>
                          <td><input type="color" name="color" id="color" value="{{ sub_category.color }}" disabled></td>
                          <td>{{ sub_category.created_by }}</td>
                          <td>{% if sub_category.is_votable %}True{% else %}False{% endif %}</td>
                          <td>{% if sub_category.is_active %}True{% else %}False{% endif %}</td>
                          <td><a href="{% url "django_simple_forum:view_category" sub_category.slug %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_category" sub_category.slug %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:delete_category" sub_category.slug %}" class="delete-category"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% endfor %}

                        {% endfor %}
                      </tbody>
                    </table>
                    {% show_pages %}
    </div>
    </div>
    <nav class="overview-paging">
    </nav>
        {% else %}
    No Categories Available in database
    {% endif %}

  </div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.delete-category').click(function(e){
  e.preventDefault();
  href = $(this).attr('data-href');
  if (!confirm('Do you want to delete Category?'))
    return;
  $.post(href, $("form#jobform").serialize(), function(data) {
          if (data.error) {
            alert(data.response);
          } else {
            alert("Category Deleted Successfully")
            window.location = '.';
          }
        }, 'json');
  });

</script>
{% endblock %}

django_simple_forum/templates/dashboard/dashboard.html
{% extends 'dashboard/dashboard_base.html' %}

django_simple_forum/templates/dashboard/users.html
{% extends 'dashboard/dashboard_base.html' %}
{% load el_pagination_tags %}
{% block stage %}
<div class="content">
  <div class="list">
    <div class="list-header">
      <label>Users</label>
    </div>
    <div class="results-slct-items row mt">
      {% paginate 10 users_list %}
      <form name="filter_form" id="filter_form" method='post'>
        {% csrf_token %}
        <input type="text" name="search_text" id="search_text" value="{{ request.POST.search_text }}"/>
        <input type="hidden" name="filter_per_page" id="filter_per_page" value="{{ filter_per_page }}"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    {% if users_list %}
        <div class="user_table">
      <div class="table-responsive">

    <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Email</th>
                          <th>User Name</th>
                          <th>No Of Used Votes(Up/Down)</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody class="overflow:scroll;">
                        {% for user in users_list %}
                        <tr class="sub_item_trs sub_item_{{ item.item_key }}">
                          <td>{{ forloop.counter }}</td>
                          <td>{{ user.user.email }}</td>
                          <td>{{ user.user.username }}</td>
                          <td>{{ user.used_votes }}({{user.get_no_of_up_votes}}/{{user.get_no_of_down_votes}})</td>
                          <td><a href="{% url "django_simple_forum:user_detail" user.user.id %}" class=""><i class="fa fa-eye view"></i></a><a href="{% url "django_simple_forum:edit_user" user.user.id %}" class=""><i class="fa fa-edit edit"></i></a><a href="#" data-href="{% url "django_simple_forum:user_status" user.user.id %}" class="user_status" title='{% if user.user.is_active %}InActive{%  else %}Active{% endif %}'>{% if user.user.is_active %}<i class="fa fa-times edit"></i>{% else %}<i class="fa fa-check edit"></i>{% endif %}</a><a href="#" data-href="{% url "django_simple_forum:delete_user" user.user.id %}" class="delete-user"><i class="fa fa-trash delete"></i></a></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
          {% show_pages %}
    </div>
    </div>
    <nav class="overview-paging">
    </nav>
        {% else %}
    No Users Available in database
    {% endif %}

  </div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.delete-user').click(function(e){
      e.preventDefault();
      href = $(this).attr('data-href');
      if (!confirm('Do you want to delete User?'))
        return;
      $.post(href, $("form#jobform").serialize(), function(data) {
      if (data.error) {
        alert(data.response);
      } else {
        alert("User Deleted Successfully")
        window.location = '.';
      }
    }, 'json');
  });
  $('.user_status').click(function(e){
      e.preventDefault();
      href = $(this).attr('data-href');
      if (!confirm('Do you want to Change the User Status?'))
        return;
      $.post(href, $("form#jobform").serialize(), function(data) {
      if (data.error) {
        alert(data.response);
      } else {
        alert("User Status Changed Successfully")
        window.location = '.';
      }
    }, 'json');
  });

</script>
{% endblock %}